# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63355e71a2d8019a90ad052be220fbdcf7cdf07c1d8e92e8204d6b5b5f5b4587f296085a475c7a364875943dd4783164abd8d353c537ad989f2f109a5c48d1fa

test:
  secret_key_base: 1ad84bce6096980611f0c999dc236853208bff84ec32d7a3bb11e5c0b6bbd3f000ac67dcf3a65121c4dc578ff808fc3d4f5fc7ecf459190c91bf9fe49974d4aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
